import type { ArticleContent } from '../../contentTypes';

export const generatingReportsContent: ArticleContent = {
  blocks: [
    {
      type: 'heading',
      id: 'overview',
      level: 2,
      text: 'Overview',
    },
    {
      type: 'paragraph',
      text: 'The Reporting section lets you generate governance and compliance reports from your platform data. Reports can cover a single use case or your entire organization, and they\'re automatically saved for future reference.',
    },
    {
      type: 'paragraph',
      text: 'Generated reports are useful for audits, regulatory submissions, board presentations and stakeholder communications. They pull information from across the platform into structured documents that show your governance activities.',
    },
    {
      type: 'heading',
      id: 'why-reports',
      level: 2,
      text: 'Why generate reports?',
    },
    {
      type: 'paragraph',
      text: 'Reports help you demonstrate compliance, communicate governance status and meet audit requirements. They provide evidence of due diligence and document how your organization handles AI governance.',
    },
    {
      type: 'bullet-list',
      items: [
        { bold: 'Compliance documentation', text: 'Create evidence packages for regulatory requirements like the EU AI Act' },
        { bold: 'Audit readiness', text: 'Generate reports that auditors can review to verify your governance practices' },
        { bold: 'Stakeholder communication', text: 'Produce summaries for boards, executives and other stakeholders' },
        { bold: 'Historical record', text: 'Build an archive of governance status over time' },
        { bold: 'Use case documentation', text: 'Document governance activities for specific AI use cases' },
      ],
    },
    {
      type: 'image',
      src: '/images/user-guide/reporting-page.png',
      alt: 'Reporting page showing a table of generated reports with columns for report name, type of report, project/organization, date generated, and generated by',
      caption: 'The Reporting page shows all generated reports and lets you create new ones.',
    },
    {
      type: 'heading',
      id: 'report-types',
      level: 2,
      text: 'Types of reports',
    },
    {
      type: 'paragraph',
      text: 'There are two categories of reports based on scope:',
    },
    {
      type: 'icon-cards',
      items: [
        {
          icon: 'Lightbulb',
          title: 'Use case reports',
          description: 'Reports for a specific AI use case, covering its risks, compliance status and governance activities.',
        },
        {
          icon: 'Building2',
          title: 'Organization reports',
          description: 'Reports covering your entire organization\'s governance program across all frameworks.',
        },
      ],
    },
    {
      type: 'heading',
      id: 'available-report-types',
      level: 2,
      text: 'Available report types',
    },
    {
      type: 'paragraph',
      text: 'The reports you can generate depend on the framework tied to your use case. For EU AI Act use cases:',
    },
    {
      type: 'bullet-list',
      items: [
        { bold: 'Use case risks report', text: 'All risks identified for the use case with their status and mitigation measures' },
        { bold: 'Compliance tracker report', text: 'Status of compliance requirements and controls' },
        { bold: 'Assessment tracker report', text: 'Progress on governance assessments and questionnaires' },
        { bold: 'Vendors and risks report', text: 'Third-party vendors and their associated risks' },
        { bold: 'Training registry report', text: 'Training programs and completion status' },
        { bold: 'Policy manager report', text: 'Organizational policies and their lifecycle status' },
        { bold: 'Models and risks report', text: 'AI models in inventory with their risks' },
        { bold: 'All reports combined', text: 'A single document containing all report types' },
      ],
    },
    {
      type: 'paragraph',
      text: 'For ISO and other framework use cases:',
    },
    {
      type: 'bullet-list',
      items: [
        { bold: 'Use case risks report', text: 'All risks identified for the use case' },
        { bold: 'Clauses and annexes report', text: 'Status of framework clauses and annex controls' },
        { bold: 'Vendors and risks report', text: 'Third-party vendors and their associated risks' },
        { bold: 'Training registry report', text: 'Training programs and completion status' },
        { bold: 'Policy manager report', text: 'Organizational policies and their status' },
        { bold: 'Models and risks report', text: 'AI models with their risks' },
        { bold: 'All reports combined', text: 'A single document with all report types' },
      ],
    },
    {
      type: 'heading',
      id: 'generating-use-case-report',
      level: 2,
      text: 'Generating a use case report',
    },
    {
      type: 'paragraph',
      text: 'To generate a report for a specific use case:',
    },
    {
      type: 'ordered-list',
      items: [
        { text: 'Go to the Reporting section from the sidebar under Assurance' },
        { text: 'Click "Generate use case report"' },
        { text: 'Select the use case from the dropdown' },
        { text: 'Choose one or more report types (you can select multiple)' },
        { text: 'Optionally enter a custom name for the report' },
        { text: 'Click "Generate report"' },
        { text: 'The report downloads automatically and is saved to the reports list' },
      ],
    },
    {
      type: 'image',
      src: '/images/user-guide/generate-project-report.png',
      alt: 'Generate project report modal with fields for selecting a use case, report type, and custom report name',
      caption: 'Select a use case and report type to generate a use case-specific report.',
    },
    {
      type: 'callout',
      variant: 'tip',
      title: 'Selecting multiple report types',
      text: 'You can select multiple report types to generate several reports at once. Or choose "All reports combined in one file" to create a single document. This option can\'t be combined with individual selections.',
    },
    {
      type: 'heading',
      id: 'generating-org-report',
      level: 2,
      text: 'Generating an organization report',
    },
    {
      type: 'paragraph',
      text: 'To generate an organization-wide report:',
    },
    {
      type: 'ordered-list',
      items: [
        { text: 'Go to the Reporting section' },
        { text: 'Click "Generate organization report"' },
        { text: 'Select the organization from the dropdown' },
        { text: 'Select the framework for the report' },
        { text: 'Choose the report types to include' },
        { text: 'Optionally enter a custom report name' },
        { text: 'Click "Generate report"' },
      ],
    },
    {
      type: 'image',
      src: '/images/user-guide/generate-org-report.png',
      alt: 'Generate organization report modal with fields for selecting an organizational project, framework, report type, and custom report name',
      caption: 'Organization reports cover your entire governance program across selected frameworks.',
    },
    {
      type: 'heading',
      id: 'reports-list',
      level: 2,
      text: 'Managing generated reports',
    },
    {
      type: 'paragraph',
      text: 'All generated reports are saved in the reports list. The list shows:',
    },
    {
      type: 'bullet-list',
      items: [
        { bold: 'Report name', text: 'The name you gave the report or an auto-generated name' },
        { bold: 'Type of report', text: 'Which report type was generated' },
        { bold: 'Use case/Organization', text: 'The use case or organization the report covers' },
        { bold: 'Date generated', text: 'When the report was created' },
        { bold: 'Generated by', text: 'The user who created the report' },
      ],
    },
    {
      type: 'heading',
      id: 'filtering-reports',
      level: 2,
      text: 'Finding reports',
    },
    {
      type: 'paragraph',
      text: 'Use the filtering and organization tools to find specific reports:',
    },
    {
      type: 'bullet-list',
      items: [
        { bold: 'Filter', text: 'Filter by report name, type, use case, generated by or upload date' },
        { bold: 'Group by', text: 'Group reports by type, use case or who generated them' },
        { bold: 'Search', text: 'Search for reports by name' },
      ],
    },
    {
      type: 'heading',
      id: 'deleting-reports',
      level: 2,
      text: 'Deleting reports',
    },
    {
      type: 'paragraph',
      text: 'To delete a report, use the delete action in the Actions column. Deleted reports can\'t be recovered, so make sure you\'ve downloaded a copy if you need one.',
    },
    {
      type: 'callout',
      variant: 'warning',
      text: 'Think about keeping reports for audit trail purposes. Deleting removes them permanently from the system.',
    },
    {
      type: 'heading',
      id: 'best-practices',
      level: 2,
      text: 'Best practices',
    },
    {
      type: 'bullet-list',
      items: [
        { bold: 'Name reports clearly', text: 'Use descriptive names that include the date or purpose, like "Q4 2024 Compliance Report" or "Annual Board Summary"' },
        { bold: 'Generate regularly', text: 'Create reports on a regular schedule (monthly or quarterly) to track progress over time' },
        { bold: 'Keep archives', text: 'Hold on to historical reports to show governance evolution' },
        { bold: 'Use combined reports', text: 'For full documentation, the "All reports combined" option creates a single reference document' },
        { bold: 'Verify before sharing', text: 'Review generated reports before sharing with external stakeholders' },
      ],
    },
    {
      type: 'heading',
      id: 'faq',
      level: 2,
      text: 'Frequently asked questions',
    },
    {
      type: 'heading',
      id: 'faq-format',
      level: 3,
      text: 'What format are reports generated in?',
    },
    {
      type: 'paragraph',
      text: 'Reports are generated as downloadable files that open in standard document viewers. They\'re designed to be easy to share and print.',
    },
    {
      type: 'heading',
      id: 'faq-no-use-cases',
      level: 3,
      text: 'Why are the generate buttons disabled?',
    },
    {
      type: 'paragraph',
      text: 'The generate report buttons are disabled if no use cases exist yet. Create a use case first, then come back to the reporting section.',
    },
    {
      type: 'heading',
      id: 'faq-access-denied',
      level: 3,
      text: 'I received an access denied error when generating a report. What should I do?',
    },
    {
      type: 'paragraph',
      text: 'This means you may not have permission to generate reports for the selected use case. Check with your administrator to verify your role and permissions.',
    },
    {
      type: 'heading',
      id: 'faq-data-included',
      level: 3,
      text: 'What data is included in reports?',
    },
    {
      type: 'paragraph',
      text: 'Reports include current data from the platform at the time you generate them. They pull in risks, compliance status, policies, training records and other governance data relevant to the report type you chose.',
    },
    {
      type: 'heading',
      id: 'faq-scheduling',
      level: 3,
      text: 'Can I schedule automatic report generation?',
    },
    {
      type: 'paragraph',
      text: 'Reports are generated on demand right now. For regular reporting needs, set a reminder to generate reports on your preferred schedule. They\'re all saved in the list for later reference.',
    },
    {
      type: 'article-links',
      title: 'Related articles',
      items: [
        {
          collectionId: 'reporting',
          articleId: 'dashboard-analytics',
          title: 'Dashboard analytics',
          description: 'View governance metrics on the dashboard',
        },
        {
          collectionId: 'compliance',
          articleId: 'assessments',
          title: 'Compliance overview',
          description: 'Understand available compliance frameworks',
        },
      ],
    },
  ],
};
