import { Column, DataType, ForeignKey, Model, Table } from "sequelize-typescript";
import { ControlCategoryStructEUModel } from "./controlCategoryStructEU.model";
import { Role, RiskTier } from "./euActTypes";

/*

This is the new Control model(Schema) and will be replaced with the new one.
Please align other files with this

*/
export type ControlStructEU = {
  id?: number; // auto generated by database
  title: string; // gets assigned from the structure
  description: string; // gets assigned from the structure
  order_no?: number; // gets assigned from the structure
  implementation_details?: string; // won't get any values, will be filled by user
  control_category_id: number; // when control category is created, its id will be stored and assign here as FK
  article?: string;
  roles?: Role[];
  riskTiers?: RiskTier[];
};

@Table({
  tableName: "controls",
})
export class ControlStructEUModel extends Model<ControlStructEU> {
  @Column({
    type: DataType.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  })
  id?: number;

  @Column({
    type: DataType.STRING,
  })
  title!: string;

  @Column({
    type: DataType.STRING,
  })
  description!: string;

  @Column({
    type: DataType.INTEGER,
  })
  order_no?: number;

  @Column({
    type: DataType.STRING,
  })
  implementation_details?: string;

  @ForeignKey(() => ControlCategoryStructEUModel)
  @Column({
    type: DataType.INTEGER,
  })
  control_category_id!: number;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  })
  is_demo?: boolean;

  @Column({ type: DataType.TEXT })
  article?: string;

  // roles and riskTiers inherit from the parent controlcategories_struct_eu
  // via its junction tables; not stored on this table.
}
