export const DeployerDataRights = [
  {
    order_no: 1,
    title:
      "Keep logs automatically generated by the high-risk AI system, to the extent such logs are under your control, for at least six months.",
    description:
      "Deployer log retention obligation for automatically generated logs under the deployer's control (Art 26.5).",
    article: "Art. 26(5)",
    subControls: [
      {
        order_no: 1,
        title:
          "We have established a log retention policy specifying the minimum retention period (6 months or as required by applicable sector-specific or national law).",
        description:
          "Documented log retention policy covering the 6-month minimum and any sectoral extensions.",
      },
      {
        order_no: 2,
        title:
          "We have implemented technical measures to ensure automatic log storage and prevent premature deletion.",
        description: "Automated log capture, immutable storage, and deletion-protection controls.",
      },
    ],
  },
  {
    order_no: 2,
    title:
      "Use information provided by the provider under Article 13 to comply with the obligation to carry out a data protection impact assessment under GDPR Article 35.",
    description:
      "Integration of Art 13 provider information into GDPR Article 35 DPIAs (Art 26.6).",
    article: "Art. 26(6)",
    subControls: [
      {
        order_no: 1,
        title:
          "Before deploying the high-risk AI system, we have conducted or updated a DPIA that incorporates the AI system's data processing characteristics as described in the provider's instructions for use.",
        description:
          "Pre-deployment DPIA or DPIA update that incorporates the provider's instructions for use.",
      },
      {
        order_no: 2,
        title:
          "The DPIA addresses the specific risks posed by AI-assisted decision-making to the rights and freedoms of natural persons.",
        description:
          "DPIA content explicitly addresses AI-specific risks to rights and freedoms of natural persons.",
      },
    ],
  },
  {
    order_no: 3,
    title:
      "Provide affected persons with clear and meaningful explanations of the role of the AI system in the decision-making procedure and the main elements of the decision taken.",
    description:
      "Right to explanation for decisions with legal or similarly significant effects (Art 85).",
    article: "Art. 85",
    subControls: [
      {
        order_no: 1,
        title:
          "When a high-risk AI system is used to make or assist in making decisions that have legal effects or similarly significant effects on natural persons, we provide the affected person with an explanation of the AI system's role.",
        description:
          "Decision-point disclosure process describing the AI system's role in the decision.",
      },
      {
        order_no: 2,
        title:
          "The explanation covers the main elements of the decision taken, including the role the AI system played, and is provided in a clear and meaningful manner.",
        description:
          "Explanation template covering decision elements, AI role, and user-appropriate language.",
      },
      {
        order_no: 3,
        title:
          "We have established a process for affected persons to request and receive such explanations in a timely manner.",
        description:
          "Request-handling process with SLAs for delivering explanations to affected persons.",
      },
    ],
  },
];
